In [1]:
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
import os
# from tqdm.notebook import  tqdm
from tqdm import  tqdm
import talib
import datetime

import  mplfinance as mpf

import sys
sys.path.append('../../DataSource/baostock')
import datasource

In [2]:
# 这个是筛选多少天上涨多少的，
codes = datasource.get_codes()
code = codes[0]
dt = datasource.get_data(code)
dt.head()

,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,isST
date,,,,,,,,,,,,,
2010-01-04,sh.600000,5.233088,5.242676,5.072475,5.079667,5.199527,66191338,1.419984e+09,2,0.835129,1,-2.3052,0
2010-01-05,sh.600000,5.132405,5.173158,4.983779,5.118022,5.079667,115147943,2.436891e+09,2,1.452808,1,0.7551,0
2010-01-06,sh.600000,5.103639,5.106036,5.005354,5.017340,5.118022,96782575,2.034174e+09,2,1.221095,1,-1.9672,0
2010-01-07,sh.600000,5.005354,5.043709,4.866316,4.904671,5.017340,85236072,1.761801e+09,2,1.075414,1,-2.2456,0
2010-01-08,sh.600000,4.875905,4.986176,4.866316,4.959807,4.904671,65707646,1.349532e+09,2,0.829026,1,1.1241,0

In [3]:
dt.loc['2010-01-05':'2010-01-08',:]

,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,isST
date,,,,,,,,,,,,,
2010-01-05,sh.600000,5.132405,5.173158,4.983779,5.118022,5.079667,115147943,2.436891e+09,2,1.452808,1,0.7551,0
2010-01-06,sh.600000,5.103639,5.106036,5.005354,5.017340,5.118022,96782575,2.034174e+09,2,1.221095,1,-1.9672,0
2010-01-07,sh.600000,5.005354,5.043709,4.866316,4.904671,5.017340,85236072,1.761801e+09,2,1.075414,1,-2.2456,0
2010-01-08,sh.600000,4.875905,4.986176,4.866316,4.959807,4.904671,65707646,1.349532e+09,2,0.829026,1,1.1241,0

In [4]:
list(dt.index)[:10]

[Timestamp('2010-01-04 00:00:00'),
 Timestamp('2010-01-05 00:00:00'),
 Timestamp('2010-01-06 00:00:00'),
 Timestamp('2010-01-07 00:00:00'),
 Timestamp('2010-01-08 00:00:00'),
 Timestamp('2010-01-11 00:00:00'),
 Timestamp('2010-01-12 00:00:00'),
 Timestamp('2010-01-13 00:00:00'),
 Timestamp('2010-01-14 00:00:00'),
 Timestamp('2010-01-15 00:00:00')]

In [5]:
def get_ups(df:pd.DataFrame, days:int, up_ratio:float)->pd.DataFrame:
    # 获得已经过多少天，上证超过一定比例的
    # 先取得一个深拷贝
    df2 = df.copy()
    # 然后向前移动指定的天数
    df2[f'close{days}'] = df2['close'].shift(-days)
    # 这里要筛选
    return df2[df2[f'close{days}'] > up_ratio * df2['close']]

In [ ]:
_days = 30
_radio = 2

_day_before = 14 # 这一天往前的
_day_after = 60  # 这一天往后的
_day_diff = 14   # 这个天数以内的，不做第二次

_folder_name = f'{_days}天倍率{_radio}往前{_day_before}往后{_day_after}'
if not os.path.exists(_folder_name):
    os.makedirs(_folder_name) 


_dict_dates = {}

for i in tqdm(range(len(codes))):
    code = codes[i]
    dt = datasource.get_data(code)
    dt_tmp = get_ups(dt, _days, _radio).dropna()
    if not dt_tmp.empty:
        # 我这里要筛选这个图片
        for index in dt_tmp.index:
            # 首先看看有没有这个股票
            if not code in _dict_dates:
                _dict_dates[code] = []
            #查看是否相差点数以内的，就不做处理
            _diff = [abs((i-index).days) for i in _dict_dates[code]]
            _diff2 = [i for i in _diff if i <  _day_diff]
            if len(_diff2) > 0:
                continue
            _dict_dates[code].append(index)            
            _before = index - datetime.timedelta(days=_day_before) # 前面几天
            _after = index + datetime.timedelta(days=_day_after)   # 后边几天
            _df_plot = dt.loc[_before:_after,:]                         # 筛选
            # 绘图
            # 然后以这个绘图
            mydpi = 96
            fig1, _ = mpf.plot(_df_plot,
                           type='candle',
                           style='yahoo',
                           figsize =(800/mydpi,600/mydpi), 
                           volume=True,
                           axisoff=True,
                           returnfig=True, 
                           scale_padding=0.2)
            # 然后这里是保存
            _img_file = f'{code}-{index.strftime("%Y-%m-%d")}.jpg'
            _img_path = os.path.join(_folder_name, _img_file)
            fig1.savefig(_img_path,dpi=mydpi)
            plt.clf()
            plt.close()

 16%|████████████▍                                                                  | 857/5450 [10:51<40:44,  1.88it/s]